"""Local execution backend for autoresearch eval.

The remote `worker.server` and this module are two transports for the SAME
contract: extract a tar.gz package built by `task_config._build_package`,
run the auto-generated `verify_<op>.py` and `profile_<op>_*.py` scripts as
subprocesses, collect their JSON artifacts, and return a dict with the same
shape the HTTP worker returns. Because the verify/profile scripts are
generated by `task_config._gen_verify_script` / `_gen_profile_script` (which
are device-aware: cuda / npu / cpu branches built in), the local and remote
paths converge on byte-identical execution code.

Public surface:
  - detect_local_backend(backend) -> (ok, why)
  - local_verify(package_bytes, op_name, timeout, device_id=0) -> dict
  - local_profile(package_bytes, op_name, timeout, device_id=0) -> dict

This module mirrors the `collect_json_artifacts` helper from the vendored
LocalWorker but stays synchronous (subprocess.run, no asyncio) and skips
the DevicePool / roofline machinery that doesn't apply to single-developer
local iteration. It DOES wrap profile scripts with msprof (ascendc) or
nsys (cuda_c) when those CLIs are on PATH — see `_profile_via_msprof` /
`_profile_via_nsys`; the dispatcher in `local_profile` falls back to a
plain subprocess profile when the wrapper CLI / vendored helpers aren't
importable.
"""
from __future__ import annotations

import io
import json
import logging
import os
import subprocess
import sys
import tarfile
import tempfile
from typing import Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Backend detection
# ---------------------------------------------------------------------------

# Subprocess probe — keeps torch import out of the parent process so a
# half-broken install can't poison hooks/scaffold/etc.
_PROBE_SCRIPT = r"""
import sys
backend = sys.argv[1]
try:
    import torch
except Exception as e:
    print(f"NO: torch missing or broken: {e}")
    sys.exit(1)
if backend == "cuda":
    if not torch.cuda.is_available():
        print("NO: torch.cuda.is_available() is False")
        sys.exit(1)
    print(f"OK: cuda devices={torch.cuda.device_count()}")
    sys.exit(0)
if backend in ("ascend", "npu"):
    try:
        import torch_npu  # noqa: F401
    except Exception as e:
        print(f"NO: torch_npu missing: {e}")
        sys.exit(1)
    try:
        n = torch.npu.device_count()
    except Exception as e:
        print(f"NO: torch.npu unavailable: {e}")
        sys.exit(1)
    print(f"OK: npu devices={n}")
    sys.exit(0)
if backend == "cpu":
    print("OK: cpu")
    sys.exit(0)
print(f"NO: unknown backend {backend!r}")
sys.exit(1)
"""

_DETECT_CACHE: dict[str, tuple[bool, str]] = {}


def detect_local_backend(backend: Optional[str]) -> tuple[bool, str]:
    """Probe whether this machine can run eval locally for `backend`.

    Cached per-backend so repeated calls in the same Python process don't
    pay the subprocess cost. Returns (ok, human-readable reason).
    """
    key = (backend or "cpu").lower()
    if key in _DETECT_CACHE:
        return _DETECT_CACHE[key]
    probe_env = os.environ.copy()
    # Windows libiomp5 double-load workaround — same as we set for verify /
    # profile subprocesses. Without it, torch.import on Windows aborts with
    # OMP Error #15 and the probe falsely reports the backend unavailable.
    probe_env.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")
    try:
        r = subprocess.run(
            [sys.executable, "-c", _PROBE_SCRIPT, key],
            capture_output=True, text=True, timeout=30, env=probe_env,
        )
    except subprocess.TimeoutExpired:
        result = (False, "backend probe timed out (>30s)")
    except Exception as e:
        result = (False, f"backend probe failed to launch: {e}")
    else:
        line = (r.stdout or r.stderr or "").strip().splitlines()
        msg = line[-1] if line else "(no output)"
        result = (r.returncode == 0, msg)
    _DETECT_CACHE[key] = result
    return result


# ---------------------------------------------------------------------------
# Package extraction + script execution
# ---------------------------------------------------------------------------

def _extract_package(package_bytes: bytes, dst_dir: str) -> None:
    """Extract a tar.gz produced by task_config._build_package into dst_dir."""
    buf = io.BytesIO(package_bytes)
    with tarfile.open(fileobj=buf, mode="r:gz") as tar:
        tar.extractall(dst_dir)


def _build_env(device_id: int) -> dict:
    env = os.environ.copy()
    env["PYTHONUNBUFFERED"] = "1"
    env["DEVICE_ID"] = str(device_id)
    # The generated verify/profile scripts pick the right one based on
    # device_type; setting both is harmless on the wrong backend.
    env["CUDA_VISIBLE_DEVICES"] = str(device_id)
    env["ASCEND_RT_VISIBLE_DEVICES"] = str(device_id)
    # Windows libiomp5 double-load workaround (no-op on Linux).
    env["KMP_DUPLICATE_LIB_OK"] = "TRUE"
    return env


def _run_script(workdir: str, script_name: str, env: dict,
                timeout: int) -> tuple[int, str, str]:
    """subprocess.run wrapper that returns (rc, stdout, stderr).

    Returns rc=124 on timeout (matching the GNU `timeout(1)` convention) and
    an empty stdout/non-empty stderr describing the timeout. Process-group
    cleanup uses os.setsid on POSIX so a hung kernel can't leave orphan
    children; on Windows we rely on subprocess's own kill().
    """
    cmd = [sys.executable, script_name]
    popen_kwargs = {
        "cwd": workdir,
        "env": env,
        "stdout": subprocess.PIPE,
        "stderr": subprocess.PIPE,
    }
    if hasattr(os, "setsid"):
        popen_kwargs["preexec_fn"] = os.setsid

    try:
        proc = subprocess.Popen(cmd, **popen_kwargs)
    except Exception as e:
        return 1, "", f"failed to launch {script_name}: {e}"

    try:
        stdout, stderr = proc.communicate(timeout=timeout)
        return (proc.returncode or 0,
                (stdout or b"").decode(errors="replace"),
                (stderr or b"").decode(errors="replace"))
    except subprocess.TimeoutExpired:
        # Kill the whole process group when possible.
        try:
            if hasattr(os, "killpg"):
                import signal
                os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
            else:
                proc.terminate()
        except Exception:
            pass
        try:
            stdout, stderr = proc.communicate(timeout=5)
        except Exception:
            try:
                proc.kill()
            except Exception:
                pass
            stdout, stderr = b"", b""
        return (124,
                (stdout or b"").decode(errors="replace"),
                (stderr or b"").decode(errors="replace") +
                f"\n[local_worker] {script_name} timed out after {timeout}s")


def _collect_json_artifacts(directory: str) -> dict[str, str]:
    """Walk `directory` and return {relpath: file_text} for every .json /
    .jsonl file. Mirrors the vendored same-named helper but stays in stdlib."""
    artifacts: dict[str, str] = {}
    if not os.path.isdir(directory):
        return artifacts
    for root, _dirs, files in os.walk(directory):
        for fname in files:
            if not (fname.endswith(".json") or fname.endswith(".jsonl")):
                continue
            full = os.path.join(root, fname)
            rel = os.path.relpath(full, directory).replace("\\", "/")
            try:
                with open(full, "r", encoding="utf-8") as f:
                    artifacts[rel] = f.read()
            except Exception as e:
                logger.warning("local_worker: cannot read artifact %s: %s", rel, e)
    return artifacts


# ---------------------------------------------------------------------------
# verify / profile (HTTP-shaped responses)
# ---------------------------------------------------------------------------

def local_verify(package_bytes: bytes, op_name: str, timeout: int,
                 device_id: int = 0) -> dict:
    """Run verify_<op_name>.py from the package. Returns the same dict
    shape as `task_config._worker_verify`:

        {"success": bool, "log": str, "artifacts": {filename: content}}
    """
    with tempfile.TemporaryDirectory(prefix="ar_local_verify_") as tmp:
        try:
            _extract_package(package_bytes, tmp)
        except Exception as e:
            return {"success": False, "log": f"extract failed: {e}", "artifacts": {}}

        script = f"verify_{op_name}.py"
        if not os.path.isfile(os.path.join(tmp, script)):
            return {"success": False,
                    "log": f"verify script not found in package: {script}",
                    "artifacts": {}}

        env = _build_env(device_id)
        rc, stdout, stderr = _run_script(tmp, script, env, timeout)
        artifacts = _collect_json_artifacts(tmp)
        return {
            "success": rc == 0,
            "log": (stdout + ("\n" + stderr if stderr else "")).strip(),
            "artifacts": artifacts,
            "returncode": rc,
        }


def _avg_us_from_artifact(artifacts: dict, key: str) -> Optional[float]:
    raw = artifacts.get(key)
    if not raw:
        return None
    try:
        data = json.loads(raw)
    except Exception:
        return None
    val = data.get("avg_time_us")
    if isinstance(val, (int, float)) and 0 < val < float("inf"):
        return float(val)
    return None


def local_profile(package_bytes: bytes, op_name: str, timeout: int,
                  device_id: int = 0,
                  dsl: Optional[str] = None, backend: Optional[str] = None,
                  warmup: int = 10, runs: int = 100) -> dict:
    """Run profile_<op>_base.py + profile_<op>_generation.py with DSL-aware
    execution. Returns the task_config._worker_profile shape.

    Routing (mirrors the vendored LocalWorker.profile):
      - DSL in {triton_*, tilelang_*, pypto, torch, cpp}, or backend=cpu →
        direct subprocess. The adapter's benchmark_impl in the generated
        script measures timing with torch_npu.profiler / do_bench.
      - dsl=ascendc (backend=ascend) → msprof CLI wraps the script; timings
        parsed from msprof op_summary CSV by analyze_prof_data.
      - dsl=cuda_c (backend=cuda)   → nsys CLI wraps the script; timings
        parsed from nsys rep file by analyze_nsys_data.

    `dsl` / `backend` default to "" → direct subprocess (legacy behavior
    for callers that haven't been updated). Passing them enables the
    msprof/nsys branches.
    """
    dsl_l = (dsl or "").lower()
    backend_l = (backend or "").lower()

    with tempfile.TemporaryDirectory(prefix="ar_local_profile_") as tmp:
        try:
            _extract_package(package_bytes, tmp)
        except Exception as e:
            return {"success": False,
                    "log": f"extract failed: {e}",
                    "artifacts": {},
                    "gen_time": None, "base_time": None}

        env = _build_env(device_id)

        if dsl_l == "ascendc" and backend_l == "ascend":
            return _profile_via_msprof(tmp, op_name, timeout, env, warmup, runs)
        if dsl_l == "cuda_c" and backend_l == "cuda":
            return _profile_via_nsys(tmp, op_name, timeout, env, warmup, runs)
        return _profile_via_subprocess(tmp, op_name, timeout, env)


def _profile_via_subprocess(tmp: str, op_name: str, timeout: int, env: dict) -> dict:
    """Default path: run the generated scripts as plain subprocesses. The
    scripts' adapter.benchmark_impl does the timing work internally."""
    log_chunks: list[str] = []
    for mode in ("base", "generation"):
        script = f"profile_{op_name}_{mode}.py"
        if not os.path.isfile(os.path.join(tmp, script)):
            log_chunks.append(f"[local_worker] missing {script}")
            continue
        rc, stdout, stderr = _run_script(tmp, script, env, timeout)
        log_chunks.append(f"--- {script} (rc={rc}) ---")
        if stdout:
            log_chunks.append(stdout)
        if stderr:
            log_chunks.append(stderr)

    artifacts = _collect_json_artifacts(tmp)
    base_time = _avg_us_from_artifact(artifacts, "base_profile_result.json")
    gen_time = _avg_us_from_artifact(artifacts, "generation_profile_result.json")
    return {
        "success": gen_time is not None or base_time is not None,
        "log": "\n".join(log_chunks).strip(),
        "artifacts": artifacts,
        "gen_time": gen_time,
        "base_time": base_time,
    }


def _profile_via_msprof(tmp: str, op_name: str, timeout: int, env: dict,
                        warmup: int, runs: int) -> dict:
    """AscendC path: wrap each generated profile script with `msprof
    --application=`, then parse op_summary CSV for device-side op time.

    Requires msprof on PATH (shipped by CANN). If it's missing or the CLI
    errors, we fall back to the same subprocess path as the default DSLs
    so the user at least gets *some* timing rather than None.
    """
    # Import lazily — pandas is pulled in transitively; don't pay that cost
    # for users that never touch AscendC. ar_vendored sits in scripts/, two
    # levels up from this file (scripts/utils/local_worker.py).
    script_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if script_dir not in sys.path:
        sys.path.insert(0, script_dir)
    try:
        from ar_vendored.op.verifier.profiler_utils import run_msprof, analyze_prof_data
    except Exception as e:
        logger.warning("local_worker: ar_vendored.profiler_utils unavailable (%s); "
                       "falling back to direct subprocess", e)
        return _profile_via_subprocess(tmp, op_name, timeout, env)

    log_chunks: list[str] = []
    times: dict[str, Optional[float]] = {"base": None, "generation": None}

    for mode in ("base", "generation"):
        script = os.path.join(tmp, f"profile_{op_name}_{mode}.py")
        if not os.path.isfile(script):
            log_chunks.append(f"[local_worker] missing {script}")
            continue
        log_chunks.append(f"--- msprof {os.path.basename(script)} ---")
        # msprof spawns its own subprocess; we can't propagate our env easily
        # through shell=True, so export DEVICE_ID/ASCEND_RT_VISIBLE_DEVICES
        # via os.environ before the call.
        prev = {k: os.environ.get(k) for k in
                ("DEVICE_ID", "ASCEND_RT_VISIBLE_DEVICES", "KMP_DUPLICATE_LIB_OK")}
        os.environ.update({k: env[k] for k in prev if k in env})
        try:
            ok, err, prof_path = run_msprof(script, op_name=op_name,
                                            task_id=mode, timeout=timeout)
        finally:
            for k, v in prev.items():
                if v is None:
                    os.environ.pop(k, None)
                else:
                    os.environ[k] = v

        if not ok or not prof_path:
            log_chunks.append(f"msprof failed: {err}")
            continue
        ok2, err2, avg_us = analyze_prof_data(prof_path, warmup, runs,
                                              op_name=op_name, task_id=mode)
        if not ok2 or not (0 < avg_us < float("inf")):
            log_chunks.append(f"analyze_prof_data failed: {err2}")
            continue
        times[mode] = avg_us
        log_chunks.append(f"{mode}: avg_time_us={avg_us:.4f} (msprof)")

    artifacts = _collect_json_artifacts(tmp)
    return {
        "success": times["generation"] is not None or times["base"] is not None,
        "log": "\n".join(log_chunks).strip(),
        "artifacts": artifacts,
        "gen_time": times["generation"],
        "base_time": times["base"],
    }


def _profile_via_nsys(tmp: str, op_name: str, timeout: int, env: dict,
                      warmup: int, runs: int) -> dict:
    """CUDA_C path: wrap each profile script with nsys, parse the rep file
    via analyze_nsys_data. Falls back to direct subprocess if nsys /
    ar_vendored.profiler_utils is unavailable."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    if script_dir not in sys.path:
        sys.path.insert(0, script_dir)
    try:
        from ar_vendored.op.verifier.profiler_utils import run_nsys, analyze_nsys_data
    except Exception as e:
        logger.warning("local_worker: ar_vendored.profiler_utils unavailable (%s); "
                       "falling back to direct subprocess", e)
        return _profile_via_subprocess(tmp, op_name, timeout, env)

    log_chunks: list[str] = []
    times: dict[str, Optional[float]] = {"base": None, "generation": None}

    for mode in ("base", "generation"):
        script = os.path.join(tmp, f"profile_{op_name}_{mode}.py")
        if not os.path.isfile(script):
            log_chunks.append(f"[local_worker] missing {script}")
            continue
        log_chunks.append(f"--- nsys {os.path.basename(script)} ---")
        prev = {k: os.environ.get(k) for k in
                ("DEVICE_ID", "CUDA_VISIBLE_DEVICES", "KMP_DUPLICATE_LIB_OK")}
        os.environ.update({k: env[k] for k in prev if k in env})
        try:
            ok, err, rep_path = run_nsys(script, op_name=op_name,
                                         task_id=mode, timeout=timeout)
        finally:
            for k, v in prev.items():
                if v is None:
                    os.environ.pop(k, None)
                else:
                    os.environ[k] = v

        if not ok or not rep_path:
            log_chunks.append(f"nsys failed: {err}")
            continue
        ok2, err2, avg_us = analyze_nsys_data(rep_path, warmup, runs,
                                              op_name=op_name, task_id=mode)
        if not ok2 or not (0 < avg_us < float("inf")):
            log_chunks.append(f"analyze_nsys_data failed: {err2}")
            continue
        times[mode] = avg_us
        log_chunks.append(f"{mode}: avg_time_us={avg_us:.4f} (nsys)")

    artifacts = _collect_json_artifacts(tmp)
    return {
        "success": times["generation"] is not None or times["base"] is not None,
        "log": "\n".join(log_chunks).strip(),
        "artifacts": artifacts,
        "gen_time": times["generation"],
        "base_time": times["base"],
    }
