"""Shared atol/rtol output comparison.

Single source of truth used by:
  - the eval-package verify script generated by package_builder._gen_verify_script
    (runs in the worker subprocess after a tarball ship-and-extract)
  - the batch-time pre-flight verify.py Tier 2 check
    (runs locally against ref/kernel files before any /autoresearch is launched)

Both call sites converged here so an `equal_nan` / dtype / diagnostic-format
divergence between "what verify.py thinks is correct" and "what autoresearch's
real eval thinks is correct" can no longer creep in. autoresearch's eval is
authoritative; this module replicates exactly what it does.

The function is dependency-light (only torch) so it can be bundled into the
worker tarball without dragging the rest of `.autoresearch/scripts/` along.
"""
from __future__ import annotations

from typing import Any


def compare_outputs(out_ref: list, out_new: list,
                    atol: float, rtol: float) -> dict:
    """torch.allclose comparison with autoresearch's exact semantics.

    Behavior (must match the eval-package verify script byte-for-byte):
      - Non-tensor outputs are silently skipped (autoresearch's eval never
        materializes scalar-only outputs through this path; mismatching only
        on the tensor outputs is the contract).
      - Tensors are detached, moved to CPU, cast to float32 (`.float()`).
        Half-precision kernels still get compared at fp32 to match the
        cached reference's dtype.
      - Shape mismatch fails fast with a shape-only diagnostic.
      - Value comparison is `torch.allclose(..., atol=atol, rtol=rtol)`,
        WITHOUT `equal_nan=True`. NaN positions in either side are treated
        as a real mismatch — same as autoresearch.

    Returns:
      {"correctness": bool,
       "diagnostics": list[str],     # one per tensor output
       "max_abs_diff": float | None, # max over all tensor outputs (None if no
                                       tensor pairs were compared)
       "atol": float, "rtol": float}
    """
    import torch  # local import: keeps this module importable without torch

    diagnostics: list[str] = []
    all_close = True
    max_abs_overall: float | None = None

    if len(out_ref) != len(out_new):
        return {
            "correctness": False,
            "diagnostics": [
                f"output count: ref={len(out_ref)} new={len(out_new)}"
            ],
            "max_abs_diff": None,
            "atol": atol, "rtol": rtol,
        }

    for i, (r, n) in enumerate(zip(out_ref, out_new)):
        # Mirror autoresearch's verify script: only tensor pairs participate.
        if not (isinstance(r, torch.Tensor) and isinstance(n, torch.Tensor)):
            continue

        rf = r.detach().cpu().float()
        nf = n.detach().cpu().float()

        if rf.shape != nf.shape:
            all_close = False
            diagnostics.append(
                f"out{i} shape {tuple(rf.shape)} != kernel {tuple(nf.shape)}"
            )
            continue

        abs_diff = (rf - nf).abs()
        max_abs = float(abs_diff.max().item())
        if max_abs_overall is None or max_abs > max_abs_overall:
            max_abs_overall = max_abs

        if not torch.allclose(rf, nf, atol=atol, rtol=rtol):
            all_close = False
            rel_denom = rf.abs().clamp_min(1e-12)
            max_rel = float((abs_diff / rel_denom).max().item())
            n_bad = int((abs_diff > (atol + rtol * rf.abs())).sum().item())
            n_tot = int(rf.numel())
            diagnostics.append(
                f"out{i}: max_abs={max_abs:.3e} max_rel={max_rel:.3e} "
                f"bad_elems={n_bad}/{n_tot} ({100.0 * n_bad / n_tot:.2f}%)"
            )
        else:
            diagnostics.append(f"out{i}: OK (max_abs={max_abs:.3e})")

    return {
        "correctness": all_close,
        "diagnostics": diagnostics,
        "max_abs_diff": max_abs_overall,
        "atol": atol, "rtol": rtol,
    }


def compare_outputs_per_case(out_ref_per_case: list,
                             out_new_per_case: list,
                             atol: float, rtol: float) -> dict:
    """Multi-shape allclose-style check: hard-gate on every case.

    Inputs are List[List[Tensor]] - one outer entry per shape case, each
    inner list is the model's outputs for that case (already moved to CPU
    by the caller). Returns:

      {"correctness": bool,                 # AND of every case
       "per_case": [
           {"idx": int, "correctness": bool, "diagnostics": [...],
            "max_abs_diff": float | None}, ...
       ],
       "max_abs_diff": float | None,        # max over all cases
       "diagnostics": [str, ...],           # flat aggregate, prefixed [case i]
       "failed_indices": list[int],
       "worst_idx": int | None,
       "worst_max_abs_diff": float | None,
       "atol": float, "rtol": float}

    Both single- and multi-shape callers go through this wrapper - the
    generated verify script (worker subprocess) and the batch Tier-2 verify
    call it unconditionally, with single-shape inputs collapsed to
    `List[List[Tensor]]` of length 1.

    On multi-case failure, appends one CORRECTNESS_SUMMARY line to the
    aggregate diagnostics that failure_extractor.multi_shape_correctness_fail
    parses. The single-case path skips this summary (the per-case "outI"
    diagnostics already convey the failure).
    """
    if len(out_ref_per_case) != len(out_new_per_case):
        return {
            "correctness": False,
            "per_case": [],
            "diagnostics": [
                f"case count: ref={len(out_ref_per_case)} "
                f"new={len(out_new_per_case)}"
            ],
            "max_abs_diff": None,
            "failed_indices": [],
            "worst_idx": None,
            "worst_max_abs_diff": None,
            "atol": atol, "rtol": rtol,
        }

    per_case = []
    flat_diag: list[str] = []
    all_pass = True
    max_abs_overall: float | None = None

    for i, (out_ref, out_new) in enumerate(zip(out_ref_per_case,
                                               out_new_per_case)):
        sub = compare_outputs(list(out_ref), list(out_new), atol, rtol)
        per_case.append({
            "idx": i,
            "correctness": sub["correctness"],
            "diagnostics": sub["diagnostics"],
            "max_abs_diff": sub["max_abs_diff"],
        })
        if not sub["correctness"]:
            all_pass = False
        for d in sub["diagnostics"]:
            flat_diag.append(f"[case {i}] {d}")
        m = sub["max_abs_diff"]
        if m is not None and (max_abs_overall is None or m > max_abs_overall):
            max_abs_overall = m

    failed_indices = [pc["idx"] for pc in per_case if not pc["correctness"]]
    worst_idx: int | None = None
    worst_max: float | None = None
    if not all_pass:
        candidates = [pc for pc in per_case
                      if not pc["correctness"]
                      and isinstance(pc.get("max_abs_diff"), (int, float))]
        if candidates:
            best = max(candidates, key=lambda x: x["max_abs_diff"])
            worst_idx = best["idx"]
            worst_max = best["max_abs_diff"]
        # Only surface CORRECTNESS_SUMMARY when multi-case — the
        # failure_extractor pattern lives here so DIAGNOSE can pick up
        # which shape(s) broke. For single-case ops the per-case "outI"
        # lines already say everything.
        if len(per_case) > 1:
            flat_diag.append(
                f"[verify] CORRECTNESS_SUMMARY: failed={len(failed_indices)}/"
                f"{len(per_case)} failed_idx={failed_indices} "
                f"worst_case={worst_idx} max_abs="
                f"{(f'{worst_max:.3e}' if worst_max is not None else 'None')}"
            )

    return {
        "correctness": all_pass,
        "per_case": per_case,
        "diagnostics": flat_diag,
        "max_abs_diff": max_abs_overall,
        "failed_indices": failed_indices,
        "worst_idx": worst_idx,
        "worst_max_abs_diff": worst_max,
        "atol": atol, "rtol": rtol,
    }
